# Generated by Django 4.1.1 on 2023-04-14 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('managment', '0004_alter_doctor_options_alter_doctorvisit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctorvisit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='banned',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='care_about',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='is_send',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='relationship',
        ),
        migrations.CreateModel(
            name='PatienGuardianRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'banned',
                    models.BooleanField(
                        default=False,
                        help_text='Был ли он забанен опекуном через администратора',
                        verbose_name='banned',
                    ),
                ),
                (
                    'should_send_report',
                    models.BooleanField(
                        default=True, help_text='Отправлять ли отчеты об опекуемом', verbose_name='should send report'
                    ),
                ),
                (
                    'relationship',
                    models.CharField(
                        blank=True, help_text='Родство опекуна с опекуемым', max_length=150, verbose_name='relationship'
                    ),
                ),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.guardian')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.patient')),
            ],
        ),
    ]
