# Generated by Django 4.2 on 2023-04-17 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('managment', '0005_alter_doctor_options_alter_doctorvisit_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
