# Generated by Django 4.2 on 2023-04-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0006_delete_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsetting',
            name='color',
            field=models.CharField(choices=[('w', 'white'), ('b', 'black')], default='white', max_length=255, verbose_name='color'),
        ),
        migrations.CreateModel(
            name='GuardianSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('RU', 'RUSSIAN'), ('EN', 'ENGLISH')], max_length=255, verbose_name='language')),
                ('theme', models.CharField(choices=[('w', 'white'), ('b', 'black')], default='white', max_length=255, verbose_name='color')),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managment.guardian')),
            ],
        ),
    ]
