# Generated by Django 4.2 on 2023-04-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0007_alter_patientsetting_color_guardiansetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatienGuardianRelation',
            new_name='PatientGuardianRelation',
        ),
    ]
