# Generated by Django 4.2 on 2023-04-28 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0008_rename_patienguardianrelation_patientguardianrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='age',
            field=models.PositiveIntegerField(default=19, validators=[django.core.validators.MaxValueValidator(150)], verbose_name='age'),
            preserve_default=False,
        ),
    ]
