# Generated by Django 4.2 on 2023-05-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0010_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardiansetting',
            name='language',
            field=models.CharField(choices=[('RUSSIAN', 'RUSSIAN'), ('ENGLISH', 'ENGLISH')], max_length=255, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='guardiansetting',
            name='theme',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black')], default='white', max_length=255, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='patientsetting',
            name='color',
            field=models.CharField(choices=[('white', 'white'), ('black', 'black')], default='white', max_length=255, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='patientsetting',
            name='language',
            field=models.CharField(choices=[('RUSSIAN', 'RUSSIAN'), ('ENGLISH', 'ENGLISH')], max_length=255, verbose_name='language'),
        ),
    ]
