# Generated by Django 4.2 on 2023-05-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0011_alter_guardiansetting_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardiansetting',
            name='patient_current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.patient'),
        ),
    ]
