# Generated by Django 4.1.1 on 2023-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medicine', '0002_alter_cure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cure',
            name='dose_type',
            field=models.CharField(choices=[('pcs', 'pcs'), ('ml', 'ml')], max_length=255, verbose_name='dose type'),
        ),
        migrations.AlterField(
            model_name='cure',
            name='type',
            field=models.CharField(
                choices=[
                    ('injection', 'injection'),
                    ('ampule', 'ampule'),
                    ('pill', 'pill'),
                    ('suspension', 'suspension'),
                ],
                max_length=255,
                verbose_name='type',
            ),
        ),
    ]
