# Generated by Django 4.1.1 on 2023-05-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('medicine', '0003_alter_cure_dose_type_alter_cure_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
    ]
